### ISSUE TITLE
Disconnected from Redis (unknown POSIX error)

### ISSUE THREAD

**Issue by veverkap** [edgurgel/verk#27] opened 2016-02-20 02:26 UTC
I've got a number of errors in my log for 

```
02:24:50.005 [error] Disconnected from Redis (redis.cache.amazonaws.com:6379): unknown POSIX error
```

The GenServer doesn't die, but it seems that 0.3.4 of redix fixed this.  (See https://github.com/whatyouhide/redix/issues/19)

Can you advise?

**Comment by veverkap** [comment] 2016-02-20 02:27
FWIW, I do not use a password on my ElasticCache redis

**Comment by edgurgel** [comment] 2016-02-20 11:44
Is there any other logged message after or before this? Is this affecting Verk?

I will investigate soon as we are using ElasticCache too!

Having this [proposed change](https://github.com/whatyouhide/redix/issues/20) would help a lot to understand what's happening

**Comment by veverkap** [comment] 2016-02-20 13:35
No that is the only message logged.

On Saturday, February 20, 2016, Eduardo Gurgel <notifications@github.com>
wrote:

> Is there any other logged message after or before this? Is this affecting
> Verk?
>
> I will investigate soon as we are using ElasticCache too!
>
> Having this proposed change
> <https://github.com/whatyouhide/redix/issues/20> would help a lot to
> understand what's happening
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/edgurgel/verk/issues/27#issuecomment-186577093>.
>


-- 
Sent from Gmail Mobile

**Comment by edgurgel** [comment] 2016-02-28 10:33
I will update Redix as soon as a new stable version is released with this change: https://github.com/whatyouhide/redix/pull/22

**Comment by veverkap** [comment] 2016-02-28 16:27
Perfect.  Thanks.

**Comment by edgurgel** [comment] 2016-03-10 09:36
Done. If you run mix `deps.update verk` it should go to `0.9.9` and Redix `0.3.4`. Then we can find out more about theses logged messages.

**Comment by edgurgel** [comment] 2016-03-13 23:31
Just to you know we are using the latest Verk with Elasticache and we are also seeing this:

```
[error] Error connecting to Redis (REMOVED.cache.amazonaws.com:6379): :timeout
```

So elasticache is timing out.

I also noticed that Redix Connection is crashing due to the server timeout (I think?)

```
 =CRASH REPORT==== 13-Mar-2016::22:54:33 ===
 crasher:
 initial call: Elixir.Redix.Connection:init/1
 pid: <0.10407.0>
 registered_name: []
 exception exit: timeout
 in function  'Elixir.Connection':enter_stop/5 (lib/connection.ex, line 687)
```

I'm trying to find an easy way to set up something like `ToxyProxy` so I can track down what's happening and see why Redix is crashing when I think it shouldn't. This is just my assumption so don't trust me cause I didn't test this thoroughly. 

Could you confirm if this is the expected behaviour, @whatyouhide ?

(Sorry if this is not the best way to interact with Redix project :P)

**Comment by whatyouhide** [comment] 2016-03-14 09:38
@edgurgel Crashing after timing out should not be the expected behaviour :\ Let me know if you manage to set up a stable way to reproduce this and I will investigate (open an issue on redix directly). Btw, `v0.3.5` is out, make sure to update to that as well :)

**Comment by edgurgel** [comment] 2016-03-14 10:03
I'm still trying to reproduce. I will open an issue as soon as I find a way to reproduce it. I'm using redix v0.3.5 :+1:  Thanks for the feedback!

**Comment by edgurgel** [comment] 2016-03-15 04:38
I'm still wondering why I didn't get this logged:

https://github.com/fishcakez/connection/blob/master/lib/connection.ex#L681-L684

```
 format = '** Generic server ~p terminating \n' ++
      '** Last message in was ~p~n' ++ ## No last message
      '** When Server state == ~p~n' ++
      '** Reason for termination == ~n** ~p~n'
    args = [report_name(name), nil, mod_state, report_reason(reason2)]
    :error_logger.format(format, args)
    exit(reason)
```
This exit is from the line 687 which outputted the Crash Report I mentioned above.

**Comment by edgurgel** [comment] 2016-03-15 04:46
I will ensure that the Logger config is set and check again. 

```
 config :logger,
        handle_otp_reports: true,
        handle_sasl_reports: true
```

**Comment by edgurgel** [comment] 2016-04-24 10:34
I will close this as next Redix versions are handling more cases of timeouts and will it support sync connect which we will use.

**Closed by edgurgel** 2016-04-24 10:34 UTC
Labels: bug

**Comment by veverkap** [comment] 2016-04-24 15:22
Is Verk targeting the latest Redix now?

**Comment by whatyouhide** [comment] 2016-04-24 15:23
Likely not yet as I haven't released the new Redix yet; me and @lexmag are working hard to test it extensively before releasing v0.4.0.

**Comment by edgurgel** [comment] 2016-04-25 23:25
@whatyouhide I would love to help you folks test when you think it's close to "stable". Maybe a release candidate? I can test with toxyproxy, etc.

**Comment by whatyouhide** [comment] 2016-05-03 15:02
@edgurgel hey, sorry for the late reply. I think we have a good Redix release candidate in master right now; do you need an `rc.0` release on hex to test it or is master ok? Btw, thanks for offering to help! 💟

**Comment by edgurgel** [comment] 2016-05-08 07:22
@whatyouhide sorry for the super late response. I will start playing with the master Redix this week. But don't hold any expectations cause you know xD. Thanks again for such a nice project ;P

**Comment by edgurgel** [comment] 2016-05-15 06:00
@whatyouhide Everything seems all good. I tested reconnections and adding latency to get timeouts. LGTM

**Comment by whatyouhide** [comment] 2016-05-15 08:27
@edgurgel this is great! 😃 I will work on Pub/Sub a bit before releaseing `v0.4.0` then, thanks so much for the help 💟
